#ifndef FONT_SELECT_H
#define FONT_SELECT_H

/*
 * Picks the font cell that suits the panel. Tables are generated by
 * tools/gen_font.py and all define the same names, so nothing downstream
 * changes.
 *
 * Both panels use the same 12x24 body cell: on the big panel that yields a
 * dense 64x20 of text, which is the point of the resolution.
 *
 * The clock is the exception. It is magnified the most, and pixel replication
 * made it visibly blocky, so a large panel gets a digits-only table rendered
 * at its final size instead.
 */

/* sdkconfig.h is not force-included by the build, so without this the test
   below is silently false and the small font is chosen. */
#ifdef ESP_PLATFORM
#include "sdkconfig.h"
#endif

#include "font_12x24.h"

#if defined(CONFIG_SCREEN_BOARD_CROWPANEL_7)
#include "font_clock.h"
#define HAVE_CLOCK_FONT 1
#endif

#endif /* FONT_SELECT_H */
