#!/usr/bin/env python3
"""Generate a bitmap font header from Menlo.

    tools/gen_font.py W H [--first N] [--last N] [--prefix NAME]

Rows are packed into ceil(W/8) bytes, MSB leftmost. Run with the system python
(/usr/bin/python3), which has PIL; the ESP-IDF python env does not.

    /usr/bin/python3 tools/gen_font.py 12 24 > main/font_12x24.h
    /usr/bin/python3 tools/gen_font.py 96 160 --first 48 --last 58 \
        --prefix CLOCK > main/font_clock.h

The clock subset is ASCII 48..58, which is '0'..'9' plus ':' -- contiguous, so
it needs no special casing.
"""
import argparse
import sys
from PIL import Image, ImageDraw, ImageFont

FONT = "/System/Library/Fonts/Menlo.ttc"
THRESHOLD = 110


def pick_size(w, h, first, last):
    """Largest size whose widest glyph still fits the cell."""
    best = None
    for size in range(6, 260):
        font = ImageFont.truetype(FONT, size)
        widest = max((font.getbbox(chr(c))[2] - font.getbbox(chr(c))[0])
                     for c in range(first, last + 1))
        ascent, descent = font.getmetrics()
        if widest <= w and ascent + descent <= h:
            best = size
    if best is None:
        sys.exit("no font size fits the cell")
    return best


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("w", type=int)
    ap.add_argument("h", type=int)
    ap.add_argument("--first", type=int, default=32)
    ap.add_argument("--last", type=int, default=126)
    ap.add_argument("--prefix", default="FONT")
    a = ap.parse_args()

    w, h, first, last, pre = a.w, a.h, a.first, a.last, a.prefix
    stride = (w + 7) // 8
    array = "font_glyphs" if pre == "FONT" else pre.lower() + "_glyphs"
    guard = "%s_TABLE_H" % pre

    size = pick_size(w, h, first, last)
    font = ImageFont.truetype(FONT, size)
    ascent, descent = font.getmetrics()
    top = (h - (ascent + descent)) // 2

    out = sys.stdout
    out.write("/* Generated by tools/gen_font.py -- do not edit by hand. */\n")
    out.write("#ifndef %s\n#define %s\n\n#include <stdint.h>\n\n" % (guard, guard))
    out.write("#define %s_W %d\n#define %s_H %d\n" % (pre, w, pre, h))
    out.write("#define %s_STRIDE %d\n" % (pre, stride))
    out.write("#define %s_FIRST %d\n#define %s_LAST %d\n\n" % (pre, first, pre, last))
    out.write("static const uint8_t %s[%d][%d] = {\n"
              % (array, last - first + 1, h * stride))

    for code in range(first, last + 1):
        img = Image.new("L", (w, h), 0)
        ImageDraw.Draw(img).text((0, top), chr(code), font=font, fill=255)
        packed = []
        for y in range(h):
            bits = 0
            for x in range(w):
                if img.getpixel((x, y)) > THRESHOLD:
                    bits |= 1 << (w - 1 - x)
            for b in range(stride):
                packed.append((bits >> (8 * (stride - 1 - b))) & 0xFF)
        label = "space" if code == 32 else chr(code)
        out.write("    { %s }, /* %s */\n"
                  % (", ".join("0x%02X" % v for v in packed), label))

    out.write("};\n\n#endif /* %s */\n" % guard)
    sys.stderr.write("%s: %dx%d cell, Menlo size %d, %d glyphs, %d bytes\n"
                     % (pre, w, h, size, last - first + 1,
                        (last - first + 1) * h * stride))


if __name__ == "__main__":
    main()
