#!/usr/bin/env python3
"""Generate main/font.h -- a bitmap font for ASCII 32..126.

Renders Menlo through PIL and thresholds to 1bpp, packing each glyph row into
ceil(W/8) bytes, MSB leftmost. Run with the system python (/usr/bin/python3),
which has PIL; the ESP-IDF python env does not.

    /usr/bin/python3 tools/gen_font.py > main/font.h
"""
import sys
from PIL import Image, ImageDraw, ImageFont

W, H = 12, 24          # cell size: 240/12 = 20 cols, 135/24 = 5 rows
FONT = "/System/Library/Fonts/Menlo.ttc"
THRESHOLD = 110
FIRST, LAST = 32, 126
STRIDE = (W + 7) // 8


def pick_size():
    """Largest size whose widest glyph still fits the cell."""
    best = None
    for size in range(8, 40):
        font = ImageFont.truetype(FONT, size)
        widest = max((font.getbbox(chr(c))[2] - font.getbbox(chr(c))[0])
                     for c in range(FIRST, LAST + 1))
        ascent, descent = font.getmetrics()
        if widest <= W and ascent + descent <= H:
            best = size
    if best is None:
        sys.exit("no font size fits the cell")
    return best


def main():
    size = pick_size()
    font = ImageFont.truetype(FONT, size)
    ascent, descent = font.getmetrics()
    top = (H - (ascent + descent)) // 2

    out = sys.stdout
    out.write("/* Generated by tools/gen_font.py -- do not edit by hand. */\n")
    out.write("#ifndef FONT_TABLE_H\n#define FONT_TABLE_H\n\n#include <stdint.h>\n\n")
    out.write("#define FONT_W %d\n#define FONT_H %d\n" % (W, H))
    out.write("#define FONT_STRIDE %d\n" % STRIDE)
    out.write("#define FONT_FIRST %d\n#define FONT_LAST %d\n\n" % (FIRST, LAST))
    out.write("static const uint8_t font_glyphs[%d][%d] = {\n"
              % (LAST - FIRST + 1, H * STRIDE))

    for code in range(FIRST, LAST + 1):
        img = Image.new("L", (W, H), 0)
        ImageDraw.Draw(img).text((0, top), chr(code), font=font, fill=255)
        packed = []
        for y in range(H):
            bits = 0
            for x in range(W):
                if img.getpixel((x, y)) > THRESHOLD:
                    bits |= 1 << (W - 1 - x)
            for b in range(STRIDE):
                packed.append((bits >> (8 * (STRIDE - 1 - b))) & 0xFF)
        label = "space" if code == 32 else chr(code)
        out.write("    { %s }, /* %s */\n"
                  % (", ".join("0x%02X" % v for v in packed), label))

    out.write("};\n\n#endif /* FONT_TABLE_H */\n")
    sys.stderr.write("font: %dx%d cell, Menlo size %d\n" % (W, H, size))


if __name__ == "__main__":
    main()
