#!/usr/bin/env python3
"""Generate main/font8x16.h -- an 8x16 bitmap font for ASCII 32..126.

Renders Menlo through PIL and thresholds to 1bpp. Run with the system python
(/usr/bin/python3), which has PIL; the ESP-IDF python env does not.

    /usr/bin/python3 tools/gen_font.py > main/font8x16.h
"""
import sys
from PIL import Image, ImageDraw, ImageFont

W, H = 8, 16
FONT = "/System/Library/Fonts/Menlo.ttc"
SIZE = 14
THRESHOLD = 110
FIRST, LAST = 32, 126


def main():
    font = ImageFont.truetype(FONT, SIZE)
    ascent, descent = font.getmetrics()
    top = (H - (ascent + descent)) // 2

    out = sys.stdout
    out.write("/* Generated by tools/gen_font.py -- do not edit by hand. */\n")
    out.write("#ifndef FONT8X16_H\n#define FONT8X16_H\n\n#include <stdint.h>\n\n")
    out.write("#define FONT_W 8\n#define FONT_H 16\n")
    out.write("#define FONT_FIRST %d\n#define FONT_LAST %d\n\n" % (FIRST, LAST))
    out.write("static const uint8_t font8x16[%d][%d] = {\n" % (LAST - FIRST + 1, H))

    for code in range(FIRST, LAST + 1):
        img = Image.new("L", (W, H), 0)
        ImageDraw.Draw(img).text((0, top), chr(code), font=font, fill=255)
        rows = []
        for y in range(H):
            bits = 0
            for x in range(W):
                if img.getpixel((x, y)) > THRESHOLD:
                    bits |= 1 << (7 - x)
            rows.append(bits)
        comment = chr(code) if code != 32 else "space"
        out.write("    { %s }, /* %s */\n"
                  % (", ".join("0x%02X" % r for r in rows), comment))

    out.write("};\n\n#endif /* FONT8X16_H */\n")


if __name__ == "__main__":
    main()
